mode_ci:
  enabled: true
  branch: "main"
path: "rubycritic/"
coverage_path: "simplecov/"
no_browser: true
threshold_score: 95
minimum_score: 80
formats:
  - html
  - json
  - console
paths:
  - "app/"
  - "lib/"
